### PR TITLE
Change array separator to match documentation (`;` -> `,`).

### PR DESCRIPTION
**Pull request by gtopper**
Also:
* Minor improvement to usage string.
* Use MixedCaps as per Go convention.

### CODE REVIEW

**Comment by yaronha** [comment]
@gtopper we need to change the other way around, that was modified to `;` so it will make sense in CSV w/o extra quotes

**Comment by gtopper** [comment]
Sure, but shouldn't this be consistent also for labels? They are currently comma-separated.

**Comment by gtopper** [comment]
Also, semicolons are not so shell friendly :-)

**Comment by gtopper** [comment]
@yaronha: Effective Go says [MixedCaps](https://golang.org/doc/effective_go.html#mixed-caps). Our Nuclio sources seem to mix MixedCaps with camelCase. SNAKE_CASE is probably not really a Go thing.

**Pull request merged**
